# Generated by Django 4.2.24 on 2025-10-09 18:59

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_ckeditor_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('top_posts', models.JSONField(default=list)),
                ('top_searches', models.JSONField(default=list)),
                ('top_referrers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('results_count', models.IntegerField(default=0)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('clicked_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='blog.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', '-created_at'], name='blog_search_query_b1bf93_idx'), models.Index(fields=['-created_at'], name='blog_search_created_389b1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferrerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer_url', models.URLField(db_index=True, max_length=500)),
                ('referrer_domain', models.CharField(db_index=True, max_length=200)),
                ('visit_count', models.IntegerField(default=1)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrers', to='blog.post')),
            ],
            options={
                'ordering': ['-visit_count', '-last_visit'],
                'indexes': [models.Index(fields=['post', '-visit_count'], name='blog_referr_post_id_cc6d17_idx'), models.Index(fields=['referrer_domain', '-visit_count'], name='blog_referr_referre_75434e_idx')],
                'unique_together': {('post', 'referrer_url')},
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent_hash', models.CharField(db_index=True, max_length=64)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.post')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', '-viewed_at'], name='blog_postvi_post_id_6afb2c_idx'), models.Index(fields=['ip_hash', 'user_agent_hash', 'post'], name='blog_postvi_ip_hash_acd6af_idx')],
            },
        ),
    ]
