# Generated by Django 4.2.24 on 2025-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_dailymetrics_alter_post_content_searchquerylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
