# Generated by Django 4.2.24 on 2025-10-11 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_imageasset_file_alter_imageasset_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, help_text="Button text (e.g. 'Visit Store')", max_length=50)),
                ('cta_url', models.URLField(blank=True, help_text='Destination URL for CTA button', max_length=500)),
                ('position', models.PositiveIntegerField(db_index=True, default=0, help_text='Order of appearance')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_images', to='blog.imageasset')),
            ],
            options={
                'verbose_name': 'Homepage Carousel',
                'verbose_name_plural': 'Homepage Carousels',
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'show_on_homepage', 'position'], name='blog_homeca_is_acti_f2a220_idx')],
            },
        ),
    ]
