# Generated by Django 4.2.24 on 2025-10-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_homecarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
