# Generated by Django 4.2.24 on 2025-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_add_seo_enhancements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="canonical_url",
            field=models.URLField(
                blank=True, help_text="Canonical URL for this post", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="legacy_urls",
            field=models.JSONField(
                blank=True, default=list, help_text="Legacy URLs for redirects"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="locale",
            field=models.CharField(
                default="en", help_text="Content locale", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="og_description",
            field=models.CharField(
                blank=True, help_text="Open Graph description", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="og_image",
            field=models.URLField(
                blank=True, help_text="Open Graph image URL", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="og_title",
            field=models.CharField(
                blank=True, help_text="Open Graph title", max_length=70
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="product_references",
            field=models.JSONField(
                blank=True, default=list, help_text="Referenced product IDs"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="schema_org",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom schema.org JSON-LD data"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="seo_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta description (max 160 chars)",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="SEO optimized title (max 70 chars)",
                max_length=70,
            ),
        ),
    ]
