# Generated by Django 4.2.24 on 2025-10-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_post_canonical_url_alter_post_legacy_urls_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOHealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("google_ping", "Google Ping"),
                            ("bing_ping", "Bing Ping"),
                            ("indexnow", "IndexNow"),
                            ("sitemap_gen", "Sitemap Generation"),
                            ("gsc_verify", "GSC Verification"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("response_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "status", "-created_at"],
                        name="blog_seohea_action_f50b35_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SEOAnalyticsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("api_hit", "API Hit"),
                            ("crawler_visit", "Crawler Visit"),
                            ("schema_request", "Schema Request"),
                            ("validation", "Validation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("object_type", models.CharField(blank=True, max_length=20)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("is_crawler", models.BooleanField(db_index=True, default=False)),
                ("crawler_name", models.CharField(blank=True, max_length=50)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="blog_seoana_event_t_8ede0a_idx",
                    ),
                    models.Index(
                        fields=["is_crawler", "-created_at"],
                        name="blog_seoana_is_craw_348b5e_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="blog_seoana_object__de67df_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IndexingQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("priority", models.IntegerField(db_index=True, default=5)),
                ("submitted_google", models.BooleanField(default=False)),
                ("submitted_bing", models.BooleanField(default=False)),
                ("submitted_indexnow", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["-priority", "created_at"],
                        name="blog_indexi_priorit_c851aa_idx",
                    )
                ],
            },
        ),
    ]
