# Generated by Django 4.2.24 on 2025-10-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_seohealthlog_seoanalyticslog_indexingqueue"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("author", "Author"),
                            ("category", "Category"),
                            ("site", "Site"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "schema_type",
                    models.CharField(
                        choices=[
                            ("BlogPosting", "Blog Posting"),
                            ("Person", "Person"),
                            ("Organization", "Organization"),
                            ("WebSite", "Web Site"),
                            ("BreadcrumbList", "Breadcrumb List"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=100)),
                ("json_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_synced"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="blog_schema_object__d41f36_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-last_synced"],
                        name="blog_schema_is_acti_6bc08b_idx",
                    ),
                ],
                "unique_together": {("object_type", "object_id", "schema_type")},
            },
        ),
    ]
