# Generated by Django 4.2.24 on 2025-10-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_schemametadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(
                blank=True, help_text="Facebook page URL", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="github_url",
            field=models.URLField(
                blank=True, help_text="GitHub profile URL", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(
                blank=True, help_text="Instagram profile URL", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="LinkedIn profile URL", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_description",
            field=models.TextField(
                default="Premium products curated for you",
                help_text="Short description of your store",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_name",
            field=models.CharField(
                default="Our Store", help_text="Name of your store", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_url",
            field=models.URLField(
                default="https://store.example.com",
                help_text="URL to your e-commerce store",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twitter_url",
            field=models.URLField(
                blank=True, help_text="Twitter profile URL", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="YouTube channel URL", max_length=500, null=True
            ),
        ),
    ]
