# Generated by Django 4.2.24 on 2025-10-13 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="comment_post_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="post_list_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="post_author_idx",
        ),
    ]
